// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Infrastructure.Data;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Domain.Entities.CompanyAccount", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("CompanyName").IsRequired().HasColumnType("text");
                    b.Property<System.DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<System.Guid>("OwnerUserId").HasColumnType("uuid");
                    b.Property<string>("RegistrationNumber").IsRequired().HasColumnType("text");
                    b.Property<string>("TaxNumber").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("CompanyAccounts");
                });

            modelBuilder.Entity("UserService.Domain.Entities.CompanyMember", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<System.Guid>("CompanyAccountId").HasColumnType("uuid");
                    b.Property<string>("Role").IsRequired().HasColumnType("text");
                    b.Property<System.Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("CompanyAccountId", "UserId").IsUnique();
                    b.ToTable("CompanyMembers");
                });

            modelBuilder.Entity("UserService.Domain.Entities.GdprAuditLog", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasColumnType("text");
                    b.Property<System.DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<System.Guid>("UserProfileId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserProfileId");
                    b.ToTable("GdprAuditLogs");
                });

            modelBuilder.Entity("UserService.Domain.Entities.IdentityVerification", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("RejectionReason").HasColumnType("text");
                    b.Property<System.Guid>("UserProfileId").HasColumnType("uuid");
                    b.Property<System.DateTime?>("VerifiedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("VerificationStatus").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("UserProfileId");
                    b.ToTable("IdentityVerifications");
                });

            modelBuilder.Entity("UserService.Domain.Entities.TrustScore", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<System.DateTime>("LastCalculatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("Score").HasColumnType("integer");
                    b.Property<System.Guid>("UserProfileId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserProfileId").IsUnique();
                    b.ToTable("TrustScores");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserActivity", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasColumnType("text");
                    b.Property<System.DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<System.Guid>("UserProfileId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserProfileId");
                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserDocument", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<int>("DocumentType").HasColumnType("integer");
                    b.Property<string>("FileUrl").IsRequired().HasColumnType("text");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<System.DateTime>("UploadedAt").HasColumnType("timestamp with time zone");
                    b.Property<System.Guid>("UserProfileId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserProfileId");
                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserPack", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<System.DateTime?>("EndDate").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<int>("PackType").HasColumnType("integer");
                    b.Property<System.DateTime>("StartDate").HasColumnType("timestamp with time zone");
                    b.Property<System.Guid>("UserProfileId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserProfileId");
                    b.ToTable("UserPacks");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserPreference", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Currency").IsRequired().HasColumnType("text");
                    b.Property<string>("Language").IsRequired().HasColumnType("text");
                    b.Property<bool>("NotificationEmail").HasColumnType("boolean");
                    b.Property<bool>("NotificationPush").HasColumnType("boolean");
                    b.Property<bool>("NotificationSms").HasColumnType("boolean");
                    b.Property<System.Guid>("UserProfileId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserProfileId").IsUnique();
                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserProfile", b =>
                {
                    b.Property<System.Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Address").IsRequired().HasColumnType("text");
                    b.Property<System.Guid>("AuthUserId").HasColumnType("uuid");
                    b.Property<System.DateOnly>("BirthDate").HasColumnType("date");
                    b.Property<string>("Bio").HasColumnType("text");
                    b.Property<string>("City").IsRequired().HasColumnType("text");
                    b.Property<string>("Country").IsRequired().HasColumnType("text");
                    b.Property<System.DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<System.DateTime?>("DeletedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("FirstName").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsDeleted").HasColumnType("boolean");
                    b.Property<string>("LastName").IsRequired().HasColumnType("text");
                    b.Property<string>("PhoneNumber").IsRequired().HasColumnType("text");
                    b.Property<string>("ProfilePictureUrl").HasColumnType("text");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<System.DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("AuthUserId").IsUnique();
                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("UserService.Domain.Entities.CompanyMember", b =>
                {
                    b.HasOne("UserService.Domain.Entities.CompanyAccount", "CompanyAccount")
                        .WithMany("Members")
                        .HasForeignKey("CompanyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("CompanyAccount");
                });

            modelBuilder.Entity("UserService.Domain.Entities.GdprAuditLog", b =>
                {
                    b.HasOne("UserService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("GdprAuditLogs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.IdentityVerification", b =>
                {
                    b.HasOne("UserService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("IdentityVerifications")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.TrustScore", b =>
                {
                    b.HasOne("UserService.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("TrustScore")
                        .HasForeignKey("UserService.Domain.Entities.TrustScore", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserActivity", b =>
                {
                    b.HasOne("UserService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("UserActivities")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserDocument", b =>
                {
                    b.HasOne("UserService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("UserDocuments")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserPack", b =>
                {
                    b.HasOne("UserService.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("UserPacks")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("UserService.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("UserPreference")
                        .HasForeignKey("UserService.Domain.Entities.UserPreference", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.CompanyAccount", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("GdprAuditLogs");
                    b.Navigation("IdentityVerifications");
                    b.Navigation("TrustScore");
                    b.Navigation("UserActivities");
                    b.Navigation("UserDocuments");
                    b.Navigation("UserPacks");
                    b.Navigation("UserPreference");
                });
#pragma warning restore 612, 618
        }
    }
}
